// @ts-check

// 这在 Node.js 中运行 - 不要在这里使用客户端代码（浏览器 API，JSX...）

/**
 * 创建侧边栏可以让你：
 - 创建一个有序的文档组
 - 为该组的每个文档渲染一个侧边栏
 - 提供下一个/上一个导航

 侧边栏可以从文件系统生成，或者在这里显式定义。

 你可以创建尽可能多的侧边栏。

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
 const sidebars = {
  // 默认情况下，Docusaurus 会根据 docs 文件夹结构生成一个侧边栏,
  mixiSidebar: [{type: 'autogenerated', dirName: 'Mixi'}], // 指向根目录下的 docs/Mixi
  maimSidebar: [{type: 'autogenerated', dirName: 'MaimBot'}], // 指向根目录下的 docs/MainBot

  // 但你可以手动创建一个侧边栏
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: '教程',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;

